[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
verigrad = "3TWd8F2kC9NoDPteeRibPLWXYTBEyFxgPxCbxHybk8VS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mrlee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
