[features]
seeds = false
skip-lint = false

[programs.localnet]
verigrad = "3TWd8F2kC9NoDPteeRibPLWXYTBEyFxgPxCbxHybk8VS"

[programs.devnet]
verigrad = "BstGvvP7WHFodit1KdrzkyEoqQRyT5LfRzKxL6wmw6N6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"  # Changed from "Localnet" to "devnet"
wallet = "/Users/mrlee/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"